# Configuration

In [1]:
# Most straightforward method
import pyspark
import pandas as pd

In [2]:
spark = pyspark.sql.SparkSession.builder \
        .master('local') \
        .appName('Spark Datatype') \
        .getOrCreate()

# Import data

In [3]:
auto = spark.read.csv('auto-mpg.csv', header=True)

In [4]:
type(auto)

pyspark.sql.dataframe.DataFrame

In [5]:
auto.show()

+----+---+-----+---+------+-----+---+------+--------------------+-----+------------------+------+
| mpg|cyl|displ| hp|weight|accel| yr|origin|                name|color|              size|marker|
+----+---+-----+---+------+-----+---+------+--------------------+-----+------------------+------+
|18.0|  6|250.0| 88|  3139| 14.5| 71|    US|        ford mustang|  red|27.370336111111108|     o|
| 9.0|  8|304.0|193|  4732| 18.5| 70|    US|            hi 1200d|green|62.199511111111114|     o|
|36.1|  4| 91.0| 60|  1800| 16.4| 78|  Asia|    honda civic cvcc| blue|               9.0|     x|
|18.5|  6|250.0| 98|  3525| 19.0| 77|    US|        ford granada|  red|         34.515625|     o|
|34.3|  4| 97.0| 78|  2188| 15.8| 80|Europe|           audi 4000| blue|13.298177777777777|     s|
|32.9|  4|119.0|100|  2615| 14.8| 81|  Asia|        datsun 200sx| blue|18.995069444444447|     x|
|32.2|  4|108.0| 75|  2265| 15.2| 80|  Asia|      toyota corolla| blue|         14.250625|     x|
|22.0|  4|121.0| 76|  2511| 18.0| 72|Europe| volkswagen 411 (sw)| blue|17.514224999999996|     s|
|15.0|  8|302.0|130|  4295| 14.9| 77|    US|mercury cougar br...|green| 51.24173611111111|     o|
|17.0|  8|302.0|140|  3449| 10.5| 70|    US|         ford torino|green| 33.04333611111111|     o|
|44.0|  4| 97.0| 52|  2130| 24.6| 82|Europe|           vw pickup| blue|           12.6025|     s|
|24.5|  4|151.0| 88|  2740| 16.0| 77|    US|pontiac sunbird c...| blue|20.854444444444443|     o|
|32.0|  4|135.0| 84|  2295| 11.6| 82|    US|       dodge rampage| blue|14.630625000000002|     o|
|14.0|  8|351.0|148|  4657| 13.5| 75|    US|            ford ltd|green| 60.24346944444444|     o|
|15.0|  8|400.0|150|  3761|  9.5| 70|    US|chevrolet monte c...|green| 39.29200277777778|     o|
|13.0|  8|307.0|130|  4098| 14.0| 72|    US|chevrolet chevell...|green|           46.6489|     o|
|36.0|  4| 79.0| 58|  1825| 18.6| 77|Europe|       renault 5 gtl| blue|  9.25173611111111|     s|
|31.0|  4|119.0| 82|  2720| 19.4| 82|    US|          chevy s-10| blue| 20.55111111111111|     o|
|32.0|  4| 71.0| 65|  1836| 21.0| 74|  Asia| toyota corolla 1200| blue|            9.3636|     x|
|21.5|  3| 80.0|110|  2720| 13.5| 77|  Asia|          mazda rx-4|black| 20.55111111111111|     x|
+----+---+-----+---+------+-----+---+------+--------------------+-----+------------------+------+
only showing top 20 rows

In [6]:
auto.toPandas()

,mpg,cyl,displ,hp,weight,accel,yr,origin,name,color,size,marker
0,18.0,6,250.0,88,3139,14.5,71,US,ford mustang,red,27.370336111111108,o
1,9.0,8,304.0,193,4732,18.5,70,US,hi 1200d,green,62.199511111111114,o
2,36.1,4,91.0,60,1800,16.4,78,Asia,honda civic cvcc,blue,9.0,x
3,18.5,6,250.0,98,3525,19.0,77,US,ford granada,red,34.515625,o
4,34.3,4,97.0,78,2188,15.8,80,Europe,audi 4000,blue,13.298177777777777,s
5,32.9,4,119.0,100,2615,14.8,81,Asia,datsun 200sx,blue,18.995069444444447,x
6,32.2,4,108.0,75,2265,15.2,80,Asia,toyota corolla,blue,14.250625,x
7,22.0,4,121.0,76,2511,18.0,72,Europe,volkswagen 411 (sw),blue,17.514224999999996,s
8,15.0,8,302.0,130,4295,14.9,77,US,mercury cougar brougham,green,51.24173611111111,o
9,17.0,8,302.0,140,3449,10.5,70,US,ford torino,green,33.04333611111111,o
10,44.0,4,97.0,52,2130,24.6,82,Europe,vw pickup,blue,12.6025,s
11,24.5,4,151.0,88,2740,16.0,77,US,pontiac sunbird coupe,blue,20.854444444444443,o
12,32.0,4,135.0,84,2295,11.6,82,US,dodge rampage,blue,14.630625000000002,o
13,14.0,8,351.0,148,4657,13.5,75,US,ford ltd,green,60.24346944444444,o
14,15.0,8,400.0,150,3761,9.5,70,US,chevrolet monte carlo,green,39.29200277777778,o
15,13.0,8,307.0,130,4098,14.0,72,US,chevrolet chevelle concours (sw),green,46.6489,o
16,36.0,4,79.0,58,1825,18.6,77,Europe,renault 5 gtl,blue,9.25173611111111,s
17,31.0,4,119.0,82,2720,19.4,82,US,chevy s-10,blue,20.55111111111111,o
18,32.0,4,71.0,65,1836,21.0,74,Asia,toyota corolla 1200,blue,9.3636,x
19,21.5,3,80.0,110,2720,13.5,77,Asia,mazda rx-4,black,20.55111111111111,x
20,19.0,6,225.0,95,3264,16.0,75,US,plymouth valiant custom,red,29.593600000000006,o
21,17.0,6,231.0,110,3907,21.0,75,US,buick century,red,42.40180277777778,o
22,16.0,8,302.0,140,4141,14.0,74,US,ford gran torino,green,47.633002777777776,o
23,15.0,8,383.0,170,3563,10.0,70,US,dodge challenger se,green,35.26380277777778,o
24,23.0,4,140.0,78,2592,18.5,75,US,pontiac astro,blue,18.6624,o
25,26.0,4,98.0,90,2265,15.5,73,Europe,fiat 124 sport coupe,blue,14.250625,s
26,32.0,4,144.0,96,2665,13.9,82,Asia,toyota celica gt,blue,19.728402777777777,x
27,24.0,4,113.0,95,2372,15.0,70,Asia,toyota corona mark ii,blue,15.628844444444443,x
28,21.0,6,231.0,110,3039,15.0,75,US,buick skyhawk,red,25.654225000000004,o
29,31.3,4,120.0,75,2542,17.5,80,Asia,mazda 626,blue,17.949344444444442,x
...,...,...,...,...,...,...,...,...,...,...,...,...
362,26.0,4,97.0,46,1950,21.0,73,Europe,volkswagen super beetle,blue,10.5625,s
363,30.0,4,135.0,84,2385,12.9,81,US,plymouth reliant,blue,15.800625,o
364,29.0,4,90.0,70,1937,14.2,76,Europe,vw rabbit,blue,10.422136111111111,s
365,14.0,8,351.0,153,4154,13.5,71,US,ford galaxie 500,green,47.93254444444444,o
366,25.4,6,168.0,116,2900,12.6,81,Asia,toyota cressida,red,23.361111111111107,x
367,19.0,6,232.0,100,2901,16.0,74,US,amc hornet,red,23.377225,o
368,12.0,8,400.0,167,4906,12.5,73,US,ford country,green,66.85787777777776,o
369,20.0,4,97.0,88,2279,19.0,73,Asia,toyota carina,blue,14.427336111111112,x
370,27.0,4,97.0,88,2130,14.5,71,Asia,datsun pl510,blue,12.6025,x
371,22.3,4,140.0,88,2890,17.3,79,US,ford fairmont 4,blue,23.200277777777774,o
372,10.0,8,307.0,200,4376,15.0,70,US,chevy c20,green,53.19271111111111,o
373,19.2,8,267.0,125,3605,15.0,79,US,chevrolet malibu classic (sw),green,36.10006944444445,o
374,26.0,4,156.0,92,2585,14.5,82,US,chrysler lebaron medallion,blue,18.561736111111113,o
375,16.0,6,258.0,110,3632,18.0,74,US,amc matador,red,36.64284444444445,o
376,37.3,4,91.0,69,2130,14.7,79,Europe,fiat strada custom,blue,12.6025,s
377,26.0,4,79.0,67,1963,15.5,74,Europe,volkswagen dasher,blue,10.703802777777776,s
378,20.2,6,232.0,90,3265,18.2,79,US,amc concord dl 6,red,29.61173611111111,o
379,13.0,8,318.0,150,3755,14.0,76,US,dodge d100,green,39.16673611111111,o
380,21.0,6,199.0,90,2648,15.0,70,US,amc gremlin,red,19.47751111111111,o
381,25.0,4,90.0,71,2223,16.5,75,Europe,volkswagen dasher,blue,13.727025000000001,s
382,20.5,6,231.0,105,3425,16.9,77,US,buick skylark,red,32.58506944444444,o
383,37.7,4,89.0,62,2050,17.3,81,Asia,toyota tercel,blue,11.67361111111111,x
384,36.0,4,120.0,88,2160,14.5,82,Asia,nissan stanza xe,blue,12.96,x
385,20.0,6,156.0,122,2807,13.5,73,Asia,toyota mark ii,red,21.88680277777778,x
386,37.0,4,85.0,65,1975,19.4,81,Asia,datsun 210 mpg,blue,10.835069444444443,x
387,18.0,6,250.0,88,3021,16.5,73,US,ford maverick,red,25.351225000000003,o
388,27.0,4,151.0,90,2950,17.3,82,US,chevrolet camaro,blue,24.173611111111114,o
389,29.5,4,98.0,68,2135,16.6,78,Asia,honda accord lx,blue,12.661736111111109,x
390,17.5,6,250.0,110,3520,16.4,77,US,chevrolet concours,red,34.41777777777777,o
391,25.1,4,140.0,88,2720,15.4,78,US,ford fairmont (man),blue,20.55111111111111,o

# Data type
## Convert Spark Dataframe to RDD

In [7]:
auto_rdd = auto.rdd
auto_rdd

MapPartitionsRDD[16] at javaToPython at NativeMethodAccessorImpl.java:0

In [8]:
auto_rdd.collect()

[Row(mpg='18.0', cyl='6', displ='250.0', hp='88', weight='3139', accel='14.5', yr='71', origin='US', name='ford mustang', color='red', size='27.370336111111108', marker='o'),
 Row(mpg='9.0', cyl='8', displ='304.0', hp='193', weight='4732', accel='18.5', yr='70', origin='US', name='hi 1200d', color='green', size='62.199511111111114', marker='o'),
 Row(mpg='36.1', cyl='4', displ='91.0', hp='60', weight='1800', accel='16.4', yr='78', origin='Asia', name='honda civic cvcc', color='blue', size='9.0', marker='x'),
 Row(mpg='18.5', cyl='6', displ='250.0', hp='98', weight='3525', accel='19.0', yr='77', origin='US', name='ford granada', color='red', size='34.515625', marker='o'),
 Row(mpg='34.3', cyl='4', displ='97.0', hp='78', weight='2188', accel='15.8', yr='80', origin='Europe', name='audi 4000', color='blue', size='13.298177777777777', marker='s'),
 Row(mpg='32.9', cyl='4', displ='119.0', hp='100', weight='2615', accel='14.8', yr='81', origin='Asia', name='datsun 200sx', color='blue', size='18.995069444444447', marker='x'),
 Row(mpg='32.2', cyl='4', displ='108.0', hp='75', weight='2265', accel='15.2', yr='80', origin='Asia', name='toyota corolla', color='blue', size='14.250625', marker='x'),
 Row(mpg='22.0', cyl='4', displ='121.0', hp='76', weight='2511', accel='18.0', yr='72', origin='Europe', name='volkswagen 411 (sw)', color='blue', size='17.514224999999996', marker='s'),
 Row(mpg='15.0', cyl='8', displ='302.0', hp='130', weight='4295', accel='14.9', yr='77', origin='US', name='mercury cougar brougham', color='green', size='51.24173611111111', marker='o'),
 Row(mpg='17.0', cyl='8', displ='302.0', hp='140', weight='3449', accel='10.5', yr='70', origin='US', name='ford torino', color='green', size='33.04333611111111', marker='o'),
 Row(mpg='44.0', cyl='4', displ='97.0', hp='52', weight='2130', accel='24.6', yr='82', origin='Europe', name='vw pickup', color='blue', size='12.6025', marker='s'),
 Row(mpg='24.5', cyl='4', displ='151.0', hp='88', weight='2740', accel='16.0', yr='77', origin='US', name='pontiac sunbird coupe', color='blue', size='20.854444444444443', marker='o'),
 Row(mpg='32.0', cyl='4', displ='135.0', hp='84', weight='2295', accel='11.6', yr='82', origin='US', name='dodge rampage', color='blue', size='14.630625000000002', marker='o'),
 Row(mpg='14.0', cyl='8', displ='351.0', hp='148', weight='4657', accel='13.5', yr='75', origin='US', name='ford ltd', color='green', size='60.24346944444444', marker='o'),
 Row(mpg='15.0', cyl='8', displ='400.0', hp='150', weight='3761', accel='9.5', yr='70', origin='US', name='chevrolet monte carlo', color='green', size='39.29200277777778', marker='o'),
 Row(mpg='13.0', cyl='8', displ='307.0', hp='130', weight='4098', accel='14.0', yr='72', origin='US', name='chevrolet chevelle concours (sw)', color='green', size='46.6489', marker='o'),
 Row(mpg='36.0', cyl='4', displ='79.0', hp='58', weight='1825', accel='18.6', yr='77', origin='Europe', name='renault 5 gtl', color='blue', size='9.25173611111111', marker='s'),
 Row(mpg='31.0', cyl='4', displ='119.0', hp='82', weight='2720', accel='19.4', yr='82', origin='US', name='chevy s-10', color='blue', size='20.55111111111111', marker='o'),
 Row(mpg='32.0', cyl='4', displ='71.0', hp='65', weight='1836', accel='21.0', yr='74', origin='Asia', name='toyota corolla 1200', color='blue', size='9.3636', marker='x'),
 Row(mpg='21.5', cyl='3', displ='80.0', hp='110', weight='2720', accel='13.5', yr='77', origin='Asia', name='mazda rx-4', color='black', size='20.55111111111111', marker='x'),
 Row(mpg='19.0', cyl='6', displ='225.0', hp='95', weight='3264', accel='16.0', yr='75', origin='US', name='plymouth valiant custom', color='red', size='29.593600000000006', marker='o'),
 Row(mpg='17.0', cyl='6', displ='231.0', hp='110', weight='3907', accel='21.0', yr='75', origin='US', name='buick century', color='red', size='42.40180277777778', marker='o'),
 Row(mpg='16.0', cyl='8', displ='302.0', hp='140', weight='4141', accel='14.0', yr='74', origin='US', name='ford gran torino', color='green', size='47.633002777777776', marker='o'),
 Row(mpg='15.0', cyl='8', displ='383.0', hp='170', weight='3563', accel='10.0', yr='70', origin='US', name='dodge challenger se', color='green', size='35.26380277777778', marker='o'),
 Row(mpg='23.0', cyl='4', displ='140.0', hp='78', weight='2592', accel='18.5', yr='75', origin='US', name='pontiac astro', color='blue', size='18.6624', marker='o'),
 Row(mpg='26.0', cyl='4', displ='98.0', hp='90', weight='2265', accel='15.5', yr='73', origin='Europe', name='fiat 124 sport coupe', color='blue', size='14.250625', marker='s'),
 Row(mpg='32.0', cyl='4', displ='144.0', hp='96', weight='2665', accel='13.9', yr='82', origin='Asia', name='toyota celica gt', color='blue', size='19.728402777777777', marker='x'),
 Row(mpg='24.0', cyl='4', displ='113.0', hp='95', weight='2372', accel='15.0', yr='70', origin='Asia', name='toyota corona mark ii', color='blue', size='15.628844444444443', marker='x'),
 Row(mpg='21.0', cyl='6', displ='231.0', hp='110', weight='3039', accel='15.0', yr='75', origin='US', name='buick skyhawk', color='red', size='25.654225000000004', marker='o'),
 Row(mpg='31.3', cyl='4', displ='120.0', hp='75', weight='2542', accel='17.5', yr='80', origin='Asia', name='mazda 626', color='blue', size='17.949344444444442', marker='x'),
 Row(mpg='32.7', cyl='6', displ='168.0', hp='132', weight='2910', accel='11.4', yr='80', origin='Asia', name='datsun 280-zx', color='red', size='23.522499999999997', marker='x'),
 Row(mpg='15.0', cyl='8', displ='304.0', hp='150', weight='3892', accel='12.5', yr='72', origin='US', name='amc matador (sw)', color='green', size='42.07684444444444', marker='o'),
 Row(mpg='23.0', cyl='4', displ='140.0', hp='83', weight='2639', accel='17.0', yr='75', origin='US', name='ford pinto', color='blue', size='19.345336111111113', marker='o'),
 Row(mpg='17.6', cyl='6', displ='225.0', hp='85', weight='3465', accel='16.6', yr='81', origin='US', name='chrysler lebaron salon', color='red', size='33.350625', marker='o'),
 Row(mpg='28.0', cyl='4', displ='107.0', hp='86', weight='2464', accel='15.5', yr='76', origin='Europe', name='fiat 131', color='blue', size='16.86471111111111', marker='s'),
 Row(mpg='24.0', cyl='4', displ='116.0', hp='75', weight='2158', accel='15.5', yr='73', origin='Europe', name='opel manta', color='blue', size='12.936011111111112', marker='s'),
 Row(mpg='14.0', cyl='8', displ='302.0', hp='140', weight='4638', accel='16.0', yr='74', origin='US', name='ford gran torino (sw)', color='green', size='59.752900000000004', marker='o'),
 Row(mpg='18.1', cyl='8', displ='302.0', hp='139', weight='3205', accel='11.2', yr='78', origin='US', name='ford futura', color='green', size='28.53340277777778', marker='o'),
 Row(mpg='36.0', cyl='4', displ='98.0', hp='70', weight='2125', accel='17.3', yr='82', origin='US', name='mercury lynx l', color='blue', size='12.543402777777777', marker='o'),
 Row(mpg='29.0', cyl='4', displ='85.0', hp='52', weight='2035', accel='22.2', yr='76', origin='US', name='chevrolet chevette', color='blue', size='11.503402777777778', marker='o'),
 Row(mpg='35.1', cyl='4', displ='81.0', hp='60', weight='1760', accel='16.1', yr='81', origin='Asia', name='honda civic 1300', color='blue', size='8.604444444444443', marker='x'),
 Row(mpg='36.0', cyl='4', displ='135.0', hp='84', weight='2370', accel='13.0', yr='82', origin='US', name='dodge charger 2.2', color='blue', size='15.602500000000001', marker='o'),
 Row(mpg='16.5', cyl='8', displ='351.0', hp='138', weight='3955', accel='13.2', yr='79', origin='US', name='mercury grand marquis', color='green', size='43.450069444444445', marker='o'),
 Row(mpg='16.0', cyl='8', displ='400.0', hp='180', weight='4220', accel='11.1', yr='77', origin='US', name='pontiac grand prix lj', color='green', size='49.467777777777776', marker='o'),
 Row(mpg='29.9', cyl='4', displ='98.0', hp='65', weight='2380', accel='20.7', yr='81', origin='US', name='ford escort 2h', color='blue', size='15.734444444444446', marker='o'),
 Row(mpg='31.0', cyl='4', displ='79.0', hp='67', weight='1950', accel='19.0', yr='74', origin='Asia', name='datsun b210', color='blue', size='10.5625', marker='x'),
 Row(mpg='27.2', cyl='4', displ='119.0', hp='97', weight='2300', accel='14.7', yr='78', origin='Asia', name='datsun 510', color='blue', size='14.694444444444446', marker='x'),
 Row(mpg='14.0', cyl='8', displ='318.0', hp='150', weight='4457', accel='13.5', yr='74', origin='US', name='dodge coronet custom (sw)', color='green', size='55.18013611111112', marker='o'),
 Row(mpg='32.1', cyl='4', displ='98.0', hp='70', weight='2120', accel='15.5', yr='80', origin='US', name='chevrolet chevette', color='blue', size='12.484444444444444', marker='o'),
 Row(mpg='15.0', cyl='6', displ='250.0', hp='100', weight='3336', accel='17.0', yr='74', origin='US', name='chevrolet nova', color='red', size='30.913599999999995', marker='o'),
 Row(mpg='12.0', cyl='8', displ='383.0', hp='180', weight='4955', accel='11.5', yr='71', origin='US', name='dodge monaco (sw)', color='green', size='68.20006944444444', marker='o'),
 Row(mpg='17.6', cyl='8', displ='302.0', hp='129', weight='3725', accel='13.4', yr='79', origin='US', name='ford ltd landau', color='green', size='38.54340277777777', marker='o'),
 Row(mpg='25.0', cyl='4', displ='113.0', hp='95', weight='2228', accel='14.0', yr='71', origin='Asia', name='toyota corona', color='blue', size='13.788844444444445', marker='x'),
 Row(mpg='28.4', cyl='4', displ='151.0', hp='90', weight='2670', accel='16.0', yr='79', origin='US', name='buick skylark limited', color='blue', size='19.802500000000002', marker='o'),
 Row(mpg='29.0', cyl='4', displ='98.0', hp='83', weight='2219', accel='16.5', yr='74', origin='Europe', name='audi fox', color='blue', size='13.677669444444444', marker='s'),
 Row(mpg='30.9', cyl='4', displ='105.0', hp='75', weight='2230', accel='14.5', yr='78', origin='US', name='dodge omni', color='blue', size='13.813611111111111', marker='o'),
 Row(mpg='20.0', cyl='6', displ='232.0', hp='100', weight='2914', accel='16.0', yr='75', origin='US', name='amc gremlin', color='red', size='23.58721111111111', marker='o'),
 Row(mpg='20.8', cyl='6', displ='200.0', hp='85', weight='3070', accel='16.7', yr='78', origin='US', name='mercury zephyr', color='red', size='26.180277777777775', marker='o'),
 Row(mpg='22.0', cyl='6', displ='232.0', hp='112', weight='2835', accel='14.7', yr='82', origin='US', name='ford granada l', color='red', size='22.325624999999995', marker='o'),
 Row(mpg='38.0', cyl='4', displ='91.0', hp='67', weight='1965', accel='15.0', yr='82', origin='Asia', name='honda civic', color='blue', size='10.725624999999999', marker='x'),
 Row(mpg='31.0', cyl='4', displ='71.0', hp='65', weight='1773', accel='19.0', yr='71', origin='Asia', name='toyota corolla 1200', color='blue', size='8.732025', marker='x'),
 Row(mpg='19.0', cyl='6', displ='250.0', hp='88', weight='3302', accel='15.5', yr='71', origin='US', name='ford torino 500', color='red', size='30.286677777777772', marker='o'),
 Row(mpg='16.0', cyl='6', displ='250.0', hp='100', weight='3781', accel='17.0', yr='74', origin='US', name='chevrolet chevelle malibu classic', color='red', size='39.71100277777778', marker='o'),
 Row(mpg='25.0', cyl='4', displ='140.0', hp='75', weight='2542', accel='17.0', yr='74', origin='US', name='chevrolet vega', color='blue', size='17.949344444444442', marker='o'),
 Row(mpg='22.0', cyl='6', displ='225.0', hp='100', weight='3233', accel='15.4', yr='76', origin='US', name='plymouth valiant', color='red', size='29.034136111111113', marker='o'),
 Row(mpg='26.0', cyl='4', displ='91.0', hp='70', weight='1955', accel='20.5', yr='71', origin='US', name='plymouth cricket', color='blue', size='10.616736111111111', marker='o'),
 Row(mpg='13.0', cyl='8', displ='350.0', hp='145', weight='4055', accel='12.0', yr='76', origin='US', name='chevy c10', color='green', size='45.67506944444445', marker='o'),
 Row(mpg='19.9', cyl='8', displ='260.0', hp='110', weight='3365', accel='15.5', yr='78', origin='US', name='oldsmobile cutlass salon brougham', color='green', size='31.45340277777778', marker='o'),
 Row(mpg='11.0', cyl='8', displ='318.0', hp='210', weight='4382', accel='13.5', yr='70', origin='US', name='dodge d200', color='green', size='53.33867777777778', marker='o'),
 Row(mpg='28.0', cyl='4', displ='98.0', hp='80', weight='2164', accel='15.0', yr='72', origin='US', name='dodge colt (sw)', color='blue', size='13.008044444444444', marker='o'),
 Row(mpg='15.5', cyl='8', displ='318.0', hp='145', weight='4140', accel='13.7', yr='77', origin='US', name='dodge monaco brougham', color='green', size='47.61000000000001', marker='o'),
 Row(mpg='26.0', cyl='4', displ='96.0', hp='69', weight='2189', accel='18.0', yr='72', origin='Europe', name='renault 12 (sw)', color='blue', size='13.310336111111111', marker='s'),
 Row(mpg='14.0', cyl='8', displ='318.0', hp='150', weight='4237', accel='14.5', yr='73', origin='US', name='plymouth fury gran sedan', color='green', size='49.86713611111111', marker='o'),
 Row(mpg='12.0', cyl='8', displ='429.0', hp='198', weight='4952', accel='11.5', yr='73', origin='US', name='mercury marquis brougham', color='green', size='68.11751111111111', marker='o'),
 Row(mpg='24.2', cyl='6', displ='146.0', hp='120', weight='2930', accel='13.8', yr='81', origin='Asia', name='datsun 810 maxima', color='red', size='23.84694444444445', marker='x'),
 Row(mpg='25.0', cyl='4', displ='140.0', hp='92', weight='2572', accel='14.9', yr='76', origin='US', name='capri ii', color='blue', size='18.375511111111116', marker='o'),
 Row(mpg='22.5', cyl='6', displ='232.0', hp='90', weight='3085', accel='17.6', yr='76', origin='US', name='amc hornet', color='red', size='26.43673611111111', marker='o'),
 Row(mpg='26.8', cyl='6', displ='173.0', hp='115', weight='2700', accel='12.9', yr='79', origin='US', name='oldsmobile omega brougham', color='red', size='20.25', marker='o'),
 Row(mpg='23.0', cyl='6', displ='198.0', hp='95', weight='2904', accel='16.0', yr='73', origin='US', name='plymouth duster', color='red', size='23.4256', marker='o'),
 Row(mpg='26.0', cyl='4', displ='116.0', hp='75', weight='2246', accel='14.0', yr='74', origin='Europe', name='fiat 124 tc', color='blue', size='14.012544444444444', marker='s'),
 Row(mpg='30.7', cyl='6', displ='145.0', hp='76', weight='3160', accel='19.6', yr='81', origin='Europe', name='volvo diesel', color='red', size='27.737777777777776', marker='s'),
 Row(mpg='31.0', cyl='4', displ='79.0', hp='67', weight='2000', accel='16.0', yr='74', origin='Europe', name='fiat x1.9', color='blue', size='11.111111111111112', marker='s'),
 Row(mpg='27.2', cyl='4', displ='141.0', hp='71', weight='3190', accel='24.8', yr='79', origin='Europe', name='peugeot 504', color='blue', size='28.26694444444444', marker='s'),
 Row(mpg='21.5', cyl='6', displ='231.0', hp='115', weight='3245', accel='15.4', yr='79', origin='US', name='pontiac lemans v6', color='red', size='29.250069444444442', marker='o'),
 Row(mpg='29.0', cyl='4', displ='135.0', hp='84', weight='2525', accel='16.0', yr='82', origin='US', name='dodge aries se', color='blue', size='17.710069444444443', marker='o'),
 Row(mpg='20.0', cyl='4', displ='114.0', hp='91', weight='2582', accel='14.0', yr='73', origin='Europe', name='audi 100ls', color='blue', size='18.518677777777782', marker='s'),
 Row(mpg='13.0', cyl='8', displ='350.0', hp='150', weight='4699', accel='14.5', yr='74', origin='US', name='buick century luxus (sw)', color='green', size='61.33500277777778', marker='o'),
 Row(mpg='14.0', cyl='8', displ='440.0', hp='215', weight='4312', accel='8.5', yr='70', origin='US', name='plymouth fury iii', color='green', size='51.648177777777775', marker='o'),
 Row(mpg='38.0', cyl='4', displ='91.0', hp='67', weight='1995', accel='16.2', yr='82', origin='Asia', name='datsun 310 gx', color='blue', size='11.055625000000001', marker='x'),
 Row(mpg='13.0', cyl='8', displ='400.0', hp='175', weight='5140', accel='12.0', yr='71', origin='US', name='pontiac safari (sw)', color='green', size='73.38777777777777', marker='o'),
 Row(mpg='24.5', cyl='4', displ='98.0', hp='60', weight='2164', accel='22.1', yr='76', origin='US', name='chevrolet woody', color='blue', size='13.008044444444444', marker='o'),
 Row(mpg='13.0', cyl='8', displ='350.0', hp='175', weight='4100', accel='13.0', yr='73', origin='US', name='buick century 350', color='green', size='46.69444444444444', marker='o'),
 Row(mpg='25.0', cyl='6', displ='181.0', hp='110', weight='2945', accel='16.4', yr='82', origin='US', name='buick century limited', color='red', size='24.09173611111111', marker='o'),
 Row(mpg='24.0', cyl='4', displ='113.0', hp='95', weight='2278', accel='15.5', yr='72', origin='Asia', name='toyota corona hardtop', color='blue', size='14.41467777777778', marker='x'),
 Row(mpg='34.1', cyl='4', displ='91.0', hp='68', weight='1985', accel='16.0', yr='81', origin='Asia', name='mazda glc 4', color='blue', size='10.945069444444442', marker='x'),
 Row(mpg='13.0', cyl='8', displ='400.0', hp='150', weight='4464', accel='12.0', yr='73', origin='US', name='chevrolet caprice classic', color='green', size='55.35360000000001', marker='o'),
 Row(mpg='44.6', cyl='4', displ='91.0', hp='67', weight='1850', accel='13.8', yr='80', origin='Asia', name='honda civic 1500 gl', color='blue', size='9.506944444444445', marker='x'),
 Row(mpg='20.5', cyl='6', displ='200.0', hp='95', weight='3155', accel='18.2', yr='78', origin='US', name='chevrolet malibu', color='red', size='27.650069444444448', marker='o'),
 Row(mpg='18.0', cyl='6', displ='258.0', hp='110', weight='2962', accel='13.5', yr='71', origin='US', name='amc hornet sportabout (sw)', color='red', size='24.370677777777775', marker='o'),
 Row(mpg='23.2', cyl='4', displ='156.0', hp='105', weight='2745', accel='16.7', yr='78', origin='US', name='plymouth sapporo', color='blue', size='20.930625000000003', marker='o'),
 Row(mpg='20.0', cyl='4', displ='130.0', hp='102', weight='3150', accel='15.7', yr='76', origin='Europe', name='volvo 245', color='blue', size='27.5625', marker='s'),
 Row(mpg='24.0', cyl='4', displ='121.0', hp='110', weight='2660', accel='14.0', yr='73', origin='Europe', name='saab 99le', color='blue', size='19.654444444444447', marker='s'),
 Row(mpg='25.5', cyl='4', displ='140.0', hp='89', weight='2755', accel='15.8', yr='77', origin='US', name='ford mustang ii 2+2', color='blue', size='21.083402777777778', marker='o'),
 Row(mpg='36.1', cyl='4', displ='98.0', hp='66', weight='1800', accel='14.4', yr='78', origin='US', name='ford fiesta', color='blue', size='9.0', marker='o'),
 Row(mpg='23.0', cyl='4', displ='120.0', hp='88', weight='2957', accel='17.0', yr='75', origin='Europe', name='peugeot 504', color='blue', size='24.28846944444445', marker='s'),
 Row(mpg='24.0', cyl='4', displ='90.0', hp='75', weight='2108', accel='15.5', yr='74', origin='Europe', name='fiat 128', color='blue', size='12.34351111111111', marker='s'),
 Row(mpg='18.0', cyl='6', displ='250.0', hp='78', weight='3574', accel='21.0', yr='76', origin='US', name='ford granada ghia', color='red', size='35.48187777777778', marker='o'),
 Row(mpg='26.6', cyl='8', displ='350.0', hp='105', weight='3725', accel='19.0', yr='81', origin='US', name='oldsmobile cutlass ls', color='green', size='38.54340277777777', marker='o'),
 Row(mpg='32.0', cyl='4', displ='85.0', hp='70', weight='1990', accel='17.0', yr='76', origin='Asia', name='datsun b-210', color='blue', size='11.000277777777779', marker='x'),
 Row(mpg='20.3', cyl='5', displ='131.0', hp='103', weight='2830', accel='15.9', yr='78', origin='Europe', name='audi 5000', color='purple', size='22.246944444444445', marker='s'),
 Row(mpg='27.0', cyl='4', displ='97.0', hp='60', weight='1834', accel='19.0', yr='71', origin='Europe', name='volkswagen model 111', color='blue', size='9.343211111111112', marker='s'),

In [9]:
type(auto_rdd)

pyspark.rdd.RDD

## Dataframe sample will be List

In [10]:
auto_list = auto.take(1)
auto_list

[Row(mpg='18.0', cyl='6', displ='250.0', hp='88', weight='3139', accel='14.5', yr='71', origin='US', name='ford mustang', color='red', size='27.370336111111108', marker='o')]

In [11]:
type(auto_list)

list

## Convert List to Dataframe

In [12]:
auto_df = spark.sparkContext.parallelize(auto_list).toDF()
auto_df.show()

+----+---+-----+---+------+-----+---+------+------------+-----+------------------+------+
| mpg|cyl|displ| hp|weight|accel| yr|origin|        name|color|              size|marker|
+----+---+-----+---+------+-----+---+------+------------+-----+------------------+------+
|18.0|  6|250.0| 88|  3139| 14.5| 71|    US|ford mustang|  red|27.370336111111108|     o|
+----+---+-----+---+------+-----+---+------+------------+-----+------------------+------+

In [13]:
type(auto_df)

pyspark.sql.dataframe.DataFrame

## Convert List to RDD

In [14]:
auto_rdd = spark.sparkContext.parallelize(auto_list)
auto_rdd

ParallelCollectionRDD[28] at parallelize at PythonRDD.scala:489

In [15]:
auto_rdd.collect()

[Row(mpg='18.0', cyl='6', displ='250.0', hp='88', weight='3139', accel='14.5', yr='71', origin='US', name='ford mustang', color='red', size='27.370336111111108', marker='o')]

In [16]:
type(auto_rdd)

pyspark.rdd.RDD

## Convert RDD to Dataframe

In [17]:
auto_df = auto_rdd.toDF()
auto_df.show()

+----+---+-----+---+------+-----+---+------+------------+-----+------------------+------+
| mpg|cyl|displ| hp|weight|accel| yr|origin|        name|color|              size|marker|
+----+---+-----+---+------+-----+---+------+------------+-----+------------------+------+
|18.0|  6|250.0| 88|  3139| 14.5| 71|    US|ford mustang|  red|27.370336111111108|     o|
+----+---+-----+---+------+-----+---+------+------------+-----+------------------+------+

In [18]:
type(auto_df)

pyspark.sql.dataframe.DataFrame

## Column

In [19]:
auto['marker']

Column<b'marker'>

In [20]:
auto['marker'].getField('0')

Column<b"marker['0']">

In [21]:
auto['marker'].getItem(0)

Column<b'marker[0]'>